/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms2;
import com.sun.glass.events.KeyEvent;
import static dbms2.DbConnect.conn;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author Rohan
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1280));
        getContentPane().setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms2/TITLE.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 970, 180);

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("USERNAME");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1450, 400, 390, 50);

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("PASSWORD");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(1450, 470, 390, 50);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms2/login button.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1450, 540, 390, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Don't have account");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1560, 620, 170, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms2/create new acccount.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1450, 650, 390, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms2/buy and cell.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 640, 530);

        jLabel3.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel3.setText("Welcome !");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1570, 340, 190, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("X");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1859, 10, 40, 40);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms2/sample2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // this.setVisible(false);
        createAcc Info= new createAcc();
        Info.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql,temp_uname,temp_pass;
        sql = "select username,password from user_info where username=? and password=?";
        try{
            conn = DbConnect.javaDb();
            PreparedStatement pst1;
            pst1 = conn.prepareStatement(sql);
            
            temp_uname=jTextField1.getText();
            
            temp_pass=new String(jPasswordField1.getPassword());
            if(temp_uname.equals("")){
                JOptionPane.showMessageDialog(null,"Enter username!!!!!");
            }
            if(temp_pass.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Password!!!!!");
            }
            pst1.setString(1,temp_uname);
            pst1.setString(2,temp_pass);
            //pst1.setString(2,pwd);
            ResultSet rs;
            
            rs = pst1.executeQuery();
            if(rs.next()){
                
        
                String sql2 ="select user_id from user_info where username=? and password = ?";
                
               
                
                 
            //String sql3;
            //sql3="select user_id from user_data where username=? and password=?";
          
            try{
                
                PreparedStatement pst3;
                pst3=conn.prepareStatement(sql2);
                
                pst3.setString(1,temp_uname );
                pst3.setString(2,temp_pass );
              
                
                ResultSet rs3;
               
                rs3=pst3.executeQuery();
                
                if(rs3.next()){
               Dbms2.g_user_id =rs3.getString("user_id");
               }
            }
            catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null,e);
            } 
            
              Dbms2.page_id=0;
            Dbms2.el_cnt=0;
		main_page w=new main_page();
                w.setVisible(true);
              	this.setVisible(false);
            }else{
                
                JOptionPane.showMessageDialog(null,"Incorrect username or password","Error",JOptionPane.ERROR_MESSAGE);
                jTextField1.setText(null);
                jPasswordField1.setText(null);
            }
            
        }
             catch(SQLException | HeadlessException ex){ 
            JOptionPane.showMessageDialog(null,ex);
        
       }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String sql,temp_uname,temp_pass;
        sql = "select username,password from user_info where username=? and password=?";
        try{
            conn = DbConnect.javaDb();
            PreparedStatement pst1;
            pst1 = conn.prepareStatement(sql);
            
            temp_uname=jTextField1.getText();
            temp_pass=new String(jPasswordField1.getPassword());
            if(temp_uname.equals("")){
                JOptionPane.showMessageDialog(null,"Enter username!!!!!");
            }
            if(temp_pass.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Password!!!!!");
            }
            pst1.setString(1,temp_uname);
            pst1.setString(2,temp_pass);
            //pst1.setString(2,pwd);
            ResultSet rs;
            
            rs = pst1.executeQuery();
            if(rs.next()){
                
        
                String sql2 ="select user_id from user_info where username=? and password = ?";
                
               
                
                 
            String sql3;
            sql3="select user_id from user_data where username=? and password=?";
          
            try{
                
                PreparedStatement pst3;
                pst3=conn.prepareStatement(sql2);
                
                pst3.setString(1,temp_uname );
                pst3.setString(2,temp_pass );
              
                
                ResultSet rs3;
               
                rs3=pst3.executeQuery();
                
                if(rs3.next()){
               Dbms2.g_user_id =rs3.getString("user_id");
               }
            }
            catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null,e);
            } 
		main_page w=new main_page();
                w.setVisible(true);
              	this.setVisible(false);
            }
            
        }
             catch(SQLException | HeadlessException ex){ 
            JOptionPane.showMessageDialog(null,ex);
        
       }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(null);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        jPasswordField1.setText(null);
    }//GEN-LAST:event_jPasswordField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
