/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms2;

import static dbms2.DbConnect.conn;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Rohan
 */
public class Sell extends javax.swing.JFrame {
    String company,model,version,color,km_driven,date,fuel,transmission,category,temp_id,amount,path,car_id;
    File f;

    /**
     * Creates new form Sell
     */
    public Sell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transmissionButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        autorb = new javax.swing.JRadioButton();
        manualrb = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(540, 940));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 10, 59, 25);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 840, 310, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Version");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 210, 252, 22);

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 240, 310, 42);

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(120, 330, 310, 42);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 310, 252, 22);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Of Purchase");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 390, 252, 22);

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(120, 420, 95, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KM driven");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 460, 252, 22);

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(120, 490, 310, 42);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Category");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(330, 550, 82, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Hatchback", "Luxury", "Super Luxury", "Convertible", "Coupe", "Wagon" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(330, 580, 102, 22);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fuel Type");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 550, 82, 22);

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Diesel", "Electric" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(120, 580, 68, 22);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(120, 140, 310, 42);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Model");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 110, 50, 22);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 60, 310, 42);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Company");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 30, 252, 22);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Transmission");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 610, 250, 22);

        transmissionButtonGroup.add(autorb);
        autorb.setText("Auto");
        autorb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorbActionPerformed(evt);
            }
        });
        jPanel1.add(autorb);
        autorb.setBounds(120, 640, 100, 25);

        transmissionButtonGroup.add(manualrb);
        manualrb.setText("Manual");
        manualrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualrbActionPerformed(evt);
            }
        });
        jPanel1.add(manualrb);
        manualrb.setBounds(260, 640, 100, 25);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 680, 252, 22);

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField8);
        jTextField8.setBounds(120, 710, 310, 42);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Upload Car Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 770, 310, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 940);

        setSize(new java.awt.Dimension(540, 940));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new main_page().setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //conn=MysqlConnect.ConnectDB();
        conn = DbConnect.javaDb();

        //IdTextField.setText("1");

        company= jTextField1.getText();
        model= jTextField2.getText();
        version=jTextField3.getText();
        color= jTextField6.getText();
        km_driven= String.valueOf(jTextField4.getText());
       // date=jTextField5.getText();
       date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        autorb.setActionCommand("Auto");
        manualrb.setActionCommand("Manual");
        amount= jTextField8.getText();

        transmission=transmissionButtonGroup.getSelection().getActionCommand();
        fuel=(String)jComboBox1.getSelectedItem();
        category=(String)jComboBox2.getSelectedItem();

        String sql;
        sql="select company,model,version from car where company=? and model=? and version=?";

        try{

            PreparedStatement pst2;
            pst2=conn.prepareStatement(sql);

            pst2.setString(1, company);
            pst2.setString(2, model);
            pst2.setString(3, version);

            //JOptionPane.showMessageDialog(null,"Success");
            ResultSet rs;

            rs=pst2.executeQuery();

            if(!rs.next()){

                String query1="INSERT into car(company , model , version ,fuel_type,category )values(?,?,?,?,?)";

                try (PreparedStatement pst1 = conn.prepareStatement(query1)) {
                    pst1.setString(1,company);
                    pst1.setString(2,model);
                    pst1.setString(3,version);
                    pst1.setString(4,fuel);
                    pst1.setString(5,category);

                    pst1.executeUpdate();

                    //JOptionPane.showMessageDialog(null,"Account Created Successfully");

                }

                catch(HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }

            }

        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }

        String sql2;
        sql2="select model_id from car where company=? and model=? and version=? and fuel_type =? and category=?";

        try{

            PreparedStatement pst3;
            pst3=conn.prepareStatement(sql2);

            pst3.setString(1,company );
            pst3.setString(2,model );
            pst3.setString(3,version );
            pst3.setString(4,fuel );
            pst3.setString(5,category );

            ResultSet rs3;

            rs3=pst3.executeQuery();

            if(rs3.next()){
                temp_id =rs3.getString("model_id");
            }
            // JOptionPane.showMessageDialog(null,rs3.getString("model_id"));

            String query3="INSERT into car_info2(owner_id,model_id , color , purchase_date ,KM_driven,transmission,amount )values(?,?,?,?,?,?,?)";

            try (PreparedStatement pst4 = conn.prepareStatement(query3)) {
                pst4.setString(1,Dbms2.g_user_id);
                pst4.setString(2,temp_id);
                pst4.setString(3,color);
                pst4.setString(4,date);
                pst4.setString(5,km_driven);
                pst4.setString(6,transmission);
                pst4.setString(7,amount);

                pst4.executeUpdate();

                JOptionPane.showMessageDialog(null,"Entry added successfully");

            }

            catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }

        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }

        
        
        //images
        
        String sql3;
        sql3="SELECT MAX(`car_id`) as m FROM `car_info2`";

        try(PreparedStatement pst3 = conn.prepareStatement(sql3)){
            
            ResultSet rs = pst3.executeQuery();
            if(rs.next())
                car_id=rs.getString("m");
            
            
            
            
        }

        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        File dest = new File("C:\\Users\\Rohan\\Desktop\\New folder (2)\\"+car_id+".jpg");
              
              
        File source = new File(path);
        try {
            org.apache.commons.io.FileUtils.copyFile(source, dest);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,"error while opening file");
            e.printStackTrace();
        }
        
        
        main_page w=new main_page();
        w.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manualrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualrbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manualrbActionPerformed

    private void autorbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         JFileChooser chooser= new JFileChooser();

          FileNameExtensionFilter filter =  new FileNameExtensionFilter("Images :jpg","jpg");
     chooser.addChoosableFileFilter(filter);
          chooser.showOpenDialog(null);
        //  chooser.setPreferredSize(preferredSize);
         f= chooser.getSelectedFile();
         path=f.getAbsolutePath();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autorb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JRadioButton manualrb;
    private javax.swing.ButtonGroup transmissionButtonGroup;
    // End of variables declaration//GEN-END:variables
}
